imagenet_templates = [
    "a bad photo of a {}.",
    "a photo of many {}.",
    "a sculpture of a {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of a {}.",
    "graffiti of a {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a tattoo of a {}.",
    "the embroidered {}.",
    "a photo of a hard to see {}.",
    "a bright photo of a {}.",
    "a photo of a clean {}.",
    "a photo of a dirty {}.",
    "a dark photo of the {}.",
    "a drawing of a {}.",
    "a photo of my {}.",
    "the plastic {}.",
    "a photo of the cool {}.",
    "a close-up photo of a {}.",
    "a black and white photo of the {}.",
    "a painting of the {}.",
    "a painting of a {}.",
    "a pixelated photo of the {}.",
    "a sculpture of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of a {}.",
    "a plastic {}.",
    "a photo of the dirty {}.",
    "a jpeg corrupted photo of a {}.",
    "a blurry photo of the {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a {} in a video game.",
    "a photo of one {}.",
    "a doodle of a {}.",
    "a close-up photo of the {}.",
    "a photo of a {}.",
    "the origami {}.",
    "the {} in a video game.",
    "a sketch of a {}.",
    "a doodle of the {}.",
    "a origami {}.",
    "a low resolution photo of a {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a rendition of a {}.",
    "a photo of a nice {}.",
    "a photo of a weird {}.",
    "a blurry photo of a {}.",
    "a cartoon {}.",
    "art of a {}.",
    "a sketch of the {}.",
    "a embroidered {}.",
    "a pixelated photo of a {}.",
    "itap of the {}.",
    "a jpeg corrupted photo of the {}.",
    "a good photo of a {}.",
    "a plushie {}.",
    "a photo of the nice {}.",
    "a photo of the small {}.",
    "a photo of the weird {}.",
    "the cartoon {}.",
    "art of the {}.",
    "a drawing of the {}.",
    "a photo of the large {}.",
    "a black and white photo of a {}.",
    "the plushie {}.",
    "a dark photo of a {}.",
    "itap of a {}.",
    "graffiti of the {}.",
    "a toy {}.",
    "itap of my {}.",
    "a photo of a cool {}.",
    "a photo of a small {}.",
    "a tattoo of the {}.",
]


anchor_templates = [
    "a bad photo.",
    "a photo of many things.",
    "a sculpture.",
    "a photo of the hard to see.",
    "a low resolution photo.",
    "a rendering.",
    "graffiti.",
    "a bad photo.",
    "a cropped photo.",
    "a tattoo.",
    "an embroidery.",
    "a photo of a hard to see.",
    "a bright photo.",
    "a photo of a clean object.",
    "a photo of a dirty object.",
    "a dark photo.",
    "a drawing.",
    "a personal photo.",
    "a plastic object.",
    "a photo of the cool object.",
    "a close-up photo.",
    "a black and white photo.",
    "a painting.",
    "a painting of an object.",
    "a pixelated photo.",
    "a sculpture.",
    "a bright photo.",
    "a cropped photo of an object.",
    "a plastic object.",
    "a photo of the dirty object.",
    "a jpeg corrupted photo of an object.",
    "a blurry photo of an object.",
    "a photo of an object.",
    "a good photo of an object.",
    "a rendering of an object.",
    "an object in a video game.",
    "a photo of one object.",
    "a doodle of an object.",
    "a close-up photo of an object.",
    "a photo.",
    "an origami model.",
    "an object in a video game.",
    "sketch.",
    "doodle.",
    "origami.",
    "low resolution image.",
    "toy.",
    "rendition.",
    "photo.",
    "large image.",
    "rendition.",
    "nice image.",
    "weird image.",
    "blurry image.",
    "cartoon.",
    "art.",
    "a sketch.",
    "an embroidery.",
    "a pixelated photo.",
    "a photo taken by myself.",
    "a jpeg corrupted photo.",
    "a good photo.",
    "a plushie.",
    "a photo of the nice object.",
    "a photo of the small object.",
    "a photo of the weird object.",
    "a cartoon.",
    "art of the object.",
    "a drawing.",
    "a photo of the large object.",
    "a black and white photo.",
    "a plushie.",
    "a dark photo.",
    "a photo taken by myself.",
    "graffiti.",
    "a toy.",
    "a personal photo I took.",
    "a photo of a cool object.",
    "a photo of a small object.",
    "a tattoo.",
]
